# -*- coding: utf-8 -*-
"""MZ53781

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nk75UfPNXJjfe7ASWei6Vbgcri_VaaPP
"""

import pandas as pd

# Load dataset
data = pd.read_csv('/content/WA_Fn-UseC_-IT-Help-Desk.csv')

# Display first rows
data.head()

import nltk
import re
from nltk.corpus import stopwords

nltk.download('stopwords')

stop_words = set(stopwords.words('english'))

def preprocess(text):

    # Convert to lowercase
    text = text.lower()

    # Remove special characters
    text = re.sub(r'[^a-zA-Z]', ' ', text)

    # Tokenization
    words = text.split()

    # Stopword removal
    words = [word for word in words if word not in stop_words]

    return " ".join(words)

# Apply preprocessing
# The 'description' column was not found. Using 'FiledAgainst' instead.
data['clean_text'] = data['FiledAgainst'].apply(preprocess)

data[['FiledAgainst','clean_text']].head()

from sklearn.feature_extraction.text import TfidfVectorizer

# Convert text into numerical features
tfidf = TfidfVectorizer(max_features=5000)

X = tfidf.fit_transform(data['clean_text'])

X.shape

from sklearn.model_selection import train_test_split

y = data['TicketType'] # Changed 'category' to 'TicketType' as 'category' does not exist

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.naive_bayes import MultinomialNB

nb_model = MultinomialNB()

nb_model.fit(X_train, y_train)

nb_pred = nb_model.predict(X_test)

from sklearn.svm import LinearSVC

svm_model = LinearSVC()

svm_model.fit(X_train, y_train)

svm_pred = svm_model.predict(X_test)

from sklearn.metrics import accuracy_score

nb_accuracy = accuracy_score(y_test, nb_pred)
svm_accuracy = accuracy_score(y_test, svm_pred)

print("Naive Bayes Accuracy:", nb_accuracy)
print("SVM Accuracy:", svm_accuracy)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

cm = confusion_matrix(y_test, svm_pred)

sns.heatmap(cm, annot=True, fmt='d')

plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("Confusion Matrix")

plt.show()